export const resultInitConfig = {
  'success': true,
  'code': 20000,
  'message': '成功',
  'data': {
    'moduleCode': '8_3',
    'moduleName': '登录日志',
    'defaultCheckeds': [{
      'label': '登录模块 / Login module',
      'value': 'loginModule',
      'isChecked': true,
      'name': null,
      'code': null
    }, {'label': '登录/登出时间 /  Login/logout time', 'value': 'createTime', 'isChecked': true, 'name': null, 'code': null}, {
      'label': '登录IP / Login IP',
      'value': 'ipAddr',
      'isChecked': true,
      'name': null,
      'code': null
    }, {'label': '登录人 / Login person', 'value': 'userAccount', 'isChecked': true, 'name': null, 'code': null}, {
      'label': '登录结果 / Login result',
      'value': 'loginResult',
      'isChecked': true,
      'name': null,
      'code': null
    }],
    'checkeds': [{
      'label': '登录模块 / Login module',
      'value': 'loginModule',
      'isChecked': true,
      'name': null,
      'code': null
    }, {'label': '登录/登出时间 /  Login/logout time', 'value': 'createTime', 'isChecked': true, 'name': null, 'code': null}, {
      'label': '登录IP / Login IP',
      'value': 'ipAddr',
      'isChecked': true,
      'name': null,
      'code': null
    }, {'label': '登录人 / Login person', 'value': 'userAccount', 'isChecked': true, 'name': null, 'code': null}, {
      'label': '登录结果 / Login result',
      'value': 'loginResult',
      'isChecked': true,
      'name': null,
      'code': null
    }],
    'defaultOptions': [{
      'label': '登录模块 / Login module',
      'value': 'loginModule',
      'isChecked': true,
      'name': null,
      'code': null
    }, {'label': '登录/登出时间 /  Login/logout time', 'value': 'createTime', 'isChecked': true, 'name': null, 'code': null}, {
      'label': '登录IP / Login IP',
      'value': 'ipAddr',
      'isChecked': true,
      'name': null,
      'code': null
    }, {'label': '登录人 / Login person', 'value': 'userAccount', 'isChecked': true, 'name': null, 'code': null}, {
      'label': '登录结果 / Login result',
      'value': 'loginResult',
      'isChecked': true,
      'name': null,
      'code': null
    }],
    'options': [{
      'label': '登录模块 / Login module',
      'value': 'loginModule',
      'isChecked': true,
      'name': null,
      'code': null
    }, {'label': '登录/登出时间 /  Login/logout time', 'value': 'createTime', 'isChecked': true, 'name': null, 'code': null}, {
      'label': '登录IP / Login IP',
      'value': 'ipAddr',
      'isChecked': true,
      'name': null,
      'code': null
    }, {'label': '登录人 / Login person', 'value': 'userAccount', 'isChecked': true, 'name': null, 'code': null}, {
      'label': '登录结果 / Login result',
      'value': 'loginResult',
      'isChecked': true,
      'name': null,
      'code': null
    }],
    'defaultMouldForms': null,
    'mouldForms': null,
    'defaultSearchForm': null,
    'searchForm': null,
    'forms': [[], [{
      'id': '69611',
      'moduleCode': '8_3',
      'label': '登录模块 / Login module',
      'prop': 'loginModule',
      'required': false,
      'trigger': 'blur',
      'type': 'text',
      'renderJSX': null,
      'options': [],
      'slotAttr': null,
      'span': 11,
      'display': true,
      'sort': 0,
      'labelWidth': '110',
      'offset': 0,
      'formId': null,
      'disabled': false,
      'placeholder': '请输入登录模块 / Login module',
      'appendText': null,
      'maxlength': 20,
      'showWordLimit': false,
      'showLabel': true,
      'clearable': true,
      'defaultValue': null,
      'validator': null,
      'pattern': null,
      'slotArr': null,
      'tableColumn': [],
      'format': null,
      'requestUrl': null,
      'requestCode': null,
      'queryCondition': null,
      'selectLable': null,
      'selectValue': null,
      'selectCode': null,
      'fnType': null,
      'fnName': null
    }, {
      'id': '69612',
      'moduleCode': '8_3',
      'label': '登录人 / Login person',
      'prop': 'userAccount',
      'required': false,
      'trigger': 'blur',
      'type': 'text',
      'renderJSX': null,
      'options': [],
      'slotAttr': null,
      'span': 11,
      'display': true,
      'sort': 1,
      'labelWidth': '110',
      'offset': 1,
      'formId': null,
      'disabled': false,
      'placeholder': '请输入登录人 / Login person',
      'appendText': null,
      'maxlength': 20,
      'showWordLimit': false,
      'showLabel': true,
      'clearable': true,
      'defaultValue': null,
      'validator': null,
      'pattern': null,
      'slotArr': null,
      'tableColumn': [],
      'format': null,
      'requestUrl': null,
      'requestCode': null,
      'queryCondition': null,
      'selectLable': null,
      'selectValue': null,
      'selectCode': null,
      'fnType': null,
      'fnName': null
    }, {
      'id': '69613',
      'moduleCode': '8_3',
      'label': '登录IP / Login IP',
      'prop': 'ipAddr',
      'required': false,
      'trigger': 'blur',
      'type': 'text',
      'renderJSX': null,
      'options': [],
      'slotAttr': null,
      'span': 11,
      'display': true,
      'sort': 2,
      'labelWidth': '110',
      'offset': 0,
      'formId': null,
      'disabled': false,
      'placeholder': '请输入登录IP / Login IP',
      'appendText': null,
      'maxlength': 20,
      'showWordLimit': false,
      'showLabel': true,
      'clearable': true,
      'defaultValue': null,
      'validator': null,
      'pattern': null,
      'slotArr': null,
      'tableColumn': [],
      'format': null,
      'requestUrl': null,
      'requestCode': null,
      'queryCondition': null,
      'selectLable': null,
      'selectValue': null,
      'selectCode': null,
      'fnType': null,
      'fnName': null
    }, {
      'id': '69614',
      'moduleCode': '8_3',
      'label': '登录结果 / Login result',
      'prop': 'loginResult',
      'required': false,
      'trigger': 'change',
      'type': 'selectQuery',
      'renderJSX': null,
      'options': [{'label': '登录成功', 'value': 0, 'isChecked': null, 'name': '', 'code': ''}, {
        'label': '登录失败',
        'value': 1,
        'isChecked': null,
        'name': '',
        'code': ''
      }, {'label': '用户锁定', 'value': 2, 'isChecked': null, 'name': '', 'code': ''}, {
        'label': '退出成功',
        'value': 3,
        'isChecked': null,
        'name': '',
        'code': ''
      }],
      'slotAttr': null,
      'span': 11,
      'display': true,
      'sort': 3,
      'labelWidth': '110',
      'offset': 1,
      'formId': null,
      'disabled': false,
      'placeholder': '请选择登录结果 / Login result',
      'appendText': null,
      'maxlength': 20,
      'showWordLimit': false,
      'showLabel': true,
      'clearable': true,
      'defaultValue': null,
      'validator': null,
      'pattern': null,
      'slotArr': null,
      'tableColumn': [],
      'format': null,
      'requestUrl': null,
      'requestCode': null,
      'queryCondition': null,
      'selectLable': null,
      'selectValue': null,
      'selectCode': null,
      'fnType': null,
      'fnName': null
    }, {
      'id': '69615',
      'moduleCode': '8_3',
      'label': '起止时间',
      'prop': 'createTime',
      'required': false,
      'trigger': 'blur',
      'type': 'datetimerange',
      'renderJSX': null,
      'options': [],
      'slotAttr': null,
      'span': 11,
      'display': true,
      'sort': 4,
      'labelWidth': '110',
      'offset': 0,
      'formId': null,
      'disabled': false,
      'placeholder': '',
      'appendText': null,
      'maxlength': 20,
      'showWordLimit': false,
      'showLabel': true,
      'clearable': true,
      'defaultValue': null,
      'validator': null,
      'pattern': null,
      'slotArr': null,
      'tableColumn': [],
      'format': 'yyyy-MM-dd HH:mm:ss',
      'requestUrl': null,
      'requestCode': null,
      'queryCondition': null,
      'selectLable': null,
      'selectValue': null,
      'selectCode': null,
      'fnType': null,
      'fnName': null
    }], [], [], [], [], [], [], [], [], [], [], [], [], []],
    'isSign': null,
    'tenantId': null,
    'checkAll': true,
    'isIndeterminate': false
  }
}
